baseURL = "https://balticsecurity.github.io/site/"
languageCode = "en-us"
title = "Baltic Security Foundation"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6

publishDir = "docs"

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/headroom/headroom.js"
  [[params.plugins.js]]
  URL = "plugins/instafeed/instafeed.min.js"
  [[params.plugins.js]]
  URL = "plugins/masonry/masonry.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/smooth-scroll/smooth-scroll.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  

  
# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Publications"
  URL = "publications"
  weight = 3

  [[menu.main]]
  name = "Support & Partners"
  URL = "support"
  weight = 4

  #[[menu.main]]
  #name = "Partners"
  #URL = "partners"

[params]
logo = "images/BSF-1.png"
home = "Home"
# hompage layout ( two layout is available,  you can set the another layout by change the value of homeLayoutToggle "true" to "false")
homeLayoutToggle = true
# Meta data
description = "Baltic Security Foundation"
# about author
author = "Baltic Security Foundation"
#authorImage = "images/banner-img.png"
shortDescription = "Baltic Security Foundation"
# Contact Form Action
#contactFormAction = "images/banner-img.png"
# Google Analitycs
#googleAnalitycsID = "Your ID"
# copyright
copyright = "BSF. Designed by Andreis Purim."

  # Preloader
  [params.preloader]
  enable = true
  
  # search
  [params.search]
  enable = true

  # Instagram feed
  [params.instafeed]
  enable = false
  userID = "4044026246"
  accessToken = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"

  # footer
  [params.footer]

    #address
    [[params.footer.addresses]]
    address = "Riga, Latvia"
    

    


  # social site
  [[params.social]]
  icon = "ti-facebook"
  URL = "https://www.facebook.com/bsf.eu/"
  
  [[params.social]]
  icon = "ti-twitter-alt"
  URL = "https://twitter.com/SecurityBaltic"
  
  #[[params.social]]
  #icon = "ti-linkedin"
  #URL = "#"
  
  #[[params.social]]
  #icon = "ti-github"
  #URL = "#"
